
---
spring:
  datasource:
    url:    jdbc:mysql://localhost:3306/test
    username:   root
    password:   root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
        ddl-auto: create-drop
        show-sql: true
  application:
    name: catalogservice
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
